#try:
#    print(x)
#except NameError:
#    print("x hasn't been defined yet.")

try:
    x="Name Error Exception"
    print(y)
except NameError:
    print("Name Error Exception is Caught")